TodoList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TodoList.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TodoList/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TodoList.Models;

namespace TodoList.Controllers
{
    public class UserInfoController : Controller
    {
        
        private TodoListDbEntities db = new TodoListDbEntities();

        // GET: UserInfo
       /* public ActionResult Index()
        {
            return View(db.UserInfoes.ToList());
        }*/

        // GET: UserInfo/Details/5
        public ActionResult Login() 
        {
            
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Clear();
            return RedirectToAction("Index","Home");
        }
        [HttpPost]
        public ActionResult Login([Bind(Include = "UserName,Password")] UserInfo userInfo)
        {
            if (ModelState.IsValid) 
            {
                var a = db.UserInfoes.Where(u => u.UserName == userInfo.UserName && u.Password == userInfo.Password);
                string userName = null;
                string password = null;
                string email = null;
                int userId = 0;
                foreach (var item in a)
                {
                    System.Diagnostics.Debug.WriteLine(item.UserName);
                    System.Diagnostics.Debug.WriteLine(item.Password);
                    System.Diagnostics.Debug.WriteLine(item.Email);
                    userId = item.UserId;
                    userName = item.UserName;
                    password = item.Password;
                    email = item.Email;
                }
                if (userName != "" && userName != null) 
                {
                    FormsAuthentication.SetAuthCookie(userId.ToString(), false);
                    Session.Add("UserId", userId.ToString());

                    FormsAuthentication.SetAuthCookie(userName, false);
                    Session.Add("UserName", userName);
                }
                
            }
            

           
            return RedirectToAction("Index","TodoTables");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userInfo = db.UserInfoes.Find(id);
            if (userInfo == null)
            {
                return HttpNotFound();
            }
            return View(userInfo);
        }

        // GET: UserInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserInfo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,Password,Email")] UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                db.UserInfoes.Add(userInfo);
                db.SaveChanges();
                return RedirectToAction("Index","TodoTables");
            }

            return View(userInfo);
        }

        // GET: UserInfo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userInfo = db.UserInfoes.Find(id);
            if (userInfo == null)
            {
                return HttpNotFound();
            }
            return View(userInfo);
        }

        // POST: UserInfo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,UserName,Password,Email")] UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userInfo);
        }

        // GET: UserInfo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userInfo = db.UserInfoes.Find(id);
            if (userInfo == null)
            {
                return HttpNotFound();
            }
            return View(userInfo);
        }

        // POST: UserInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserInfo userInfo = db.UserInfoes.Find(id);
            db.UserInfoes.Remove(userInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TodoList/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TodoList/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TodoList/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron bg-white mt-5" id="Welcome">
    <h1>Todo list App</h1>
    <p class="lead">Todo List App is a free app for maintaining remainders, shopping list and more.</p>
    <p><a href="" class="btn btn-success btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4 mb-2">
        <div class="col-md-12 bg-white h-100 p-4">
            <h2>Create New Account</h2>
            <div style="height:20px;"></div>
            <p>
                Create a new account to use the best todolist app available on the market.
            </p>
            <p>@Html.ActionLink("Create Account", "Create", "UserInfo", null, new { @class = "btn btn-success" })</p>
        </div>     
    </div>
    <div class="col-md-4 mb-2">
        <div class="col-md-12 bg-white h-100 p-4">
            <h2>Login</h2>
            <p>Already created account?</p>
            <p>Jump right in!</p>
            <p>@Html.ActionLink("Login", "Login", "UserInfo", null, new { @class = "btn btn-warning" })</p>
        </div>
    </div>
    <div class="col-md-4 mb-2">
        <div class="col-md-12 bg-white h-100 p-4">
            <h2>Forgot Password</h2>
            <div style="height:25px;"></div>
            <p>Click the button below for account recovery.</p>
            <p><a class="btn btn-danger" href="https://go.microsoft.com/fwlink/?LinkId=301867">Reset &raquo;</a></p>
        </div>
    </div>
</div>